### ISSUE TITLE
IOS does not clear Keychain once the app uninstalls

### ISSUE THREAD

**Issue by AunMSheikh** [mCodex/react-native-sensitive-info#45] opened 2017-09-18 14:55 UTC
I noticed an issue when uninstalling the application the data does not get deleted, is there any way to remove data when the app uninstalls?

**Comment by evollu** [comment] 2017-09-26 17:55
that seems to be expected behavior as keychain. check ios keychain question on stackoverflow ?

**Comment by mCodex** [comment] 2017-09-26 18:26
@AunMSheikh Unfortunately, it doesn't remove, but could be a future feature in RNSInfo.

**Comment by pongponglau** [comment] 2017-11-03 03:09
Yes, i have the same issue as AunMSheikh.
But not sure if react native has an uninstall app event. If so, i can remove the keychain value when this event comes.

Thank you

**Comment by felixus95** [comment] 2018-02-14 09:16
It shouldn't in my opinion. We use it exactly for this use case. Keychain stores data to identify users, who reinstalled the application.

**Comment by mCodex** [comment] 2018-05-23 23:16
@felixus95 has a great point of view. And I agree with him. Since then, I'll close this issue now. Maybe It can be opened in the near future for more discussions.

**Closed by mCodex** 2018-05-23 23:16 UTC
Labels: enhancement, iOS

**Comment by Melber17** [comment] 2021-11-04 16:11
After uninstall and install app stored information remained.
