### ISSUE TITLE
duplicate symbol _messageForError

### ISSUE THREAD

**Issue by codehob** [mCodex/react-native-sensitive-info#6] opened 2016-10-06 17:43 UTC
duplicate symbol _messageForError in:
    /Users/iphonedeploy/Library/Developer/Xcode/DerivedData/punchinout-dbqwmosndkfyrhcrkbcebsnepfyv/Build/Products/Debug-iphonesimulator/libRNKeychain.a(RNKeychainManager.o)
    /Users/iphonedeploy/Library/Developer/Xcode/DerivedData/punchinout-dbqwmosndkfyrhcrkbcebsnepfyv/Build/Products/Debug-iphonesimulator/libRNSensitiveInfo.a(RNSensitiveInfo.o)
duplicate symbol _makeError in:
    /Users/iphonedeploy/Library/Developer/Xcode/DerivedData/punchinout-dbqwmosndkfyrhcrkbcebsnepfyv/Build/Products/Debug-iphonesimulator/libRNKeychain.a(RNKeychainManager.o)
    /Users/iphonedeploy/Library/Developer/Xcode/DerivedData/punchinout-dbqwmosndkfyrhcrkbcebsnepfyv/Build/Products/Debug-iphonesimulator/libRNSensitiveInfo.a(RNSensitiveInfo.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zibs** [comment] 2017-06-29 21:33
I'm also getting this - is there a way to resolve? Why was this closed exactly?

**Comment by mCodex** [comment] 2017-06-30 11:00
Hello @zibs , I couldn't reproduce that. Could you provide an example?

**Comment by zibs** [comment] 2017-07-17 23:17
@mCodex Sorry it took me so long to get back to you:
https://github.com/zibs/keychain-and-info-example

You should be able to just clone + `yarn` + run this on your iPhone and you will see the error. It will work on the simulator, and it works on the Android device as well. But it does not work on an actual iPhone. 

Thanks!

**Comment by mCodex** [comment] 2017-07-22 14:54
@zibs thank you!

**Comment by DavidPotter** [comment] 2017-10-10 00:06
My team is running into this as well.  It appears that this is fixed in the repo but a new version has not been published.  When will you be publishing a new version with all the changes from the past 4+ months?

**Comment by DavidPotter** [comment] 2017-10-10 00:07
Hmm, I may have posted my comment on the wrong issue.  I'm getting a different warning.  I'll open a new issue for that.  Sorry.

**Comment by mCodex** [comment] 2017-10-28 12:11
Hello Guys, is this still happening in v5.2.0 (currently beta)?

**Comment by scstan** [comment] 2017-11-12 23:09
Happens for me also on
"react-native": "0.49.3",
"react-native-sensitive-info": "^5.1.0"

**Comment by scstan** [comment] 2017-11-13 19:34
5.2.0 also

**Comment by crisppY** [comment] 2018-03-02 16:43
Yes. I'm having build errors in v5.2.0.

```
ld: warning: object file (~/app/ios/build/Build/Products/Debug-iphonesimulator/libRNKeychain.a(RNKeychainManager.o)) was built for newer iOS version (8.3) than being linked (8.0)
duplicate symbol _messageForError in:
    ~/app/ios/build/Build/Products/Debug-iphonesimulator/libRNKeychain.a(RNKeychainManager.o)
    ~/app/ios/build/Build/Products/Debug-iphonesimulator/libRNSensitiveInfo.a(RNSensitiveInfo.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by enricotelesca-ada** [comment] 2018-04-20 14:02
same here, did anyone solve?

**Comment by alexmbp** [comment] 2018-04-23 11:25
Have the same issue. Together with react-native-keychain. I believe - issue is with cocoapods while RNKeychain using pods and RN Sensitive Info does not. We have to add local pod spec to make it working. Not sure about it

**Comment by lucasbento** [comment] 2018-05-17 13:27
I had the same issue, this indeed conflicts with [react-native-keychain](https://github.com/oblador/react-native-keychain) (thanks @alexmbp).

**Comment by mCodex** [comment] 2018-05-23 23:14
Can anyone make a PR for that? Please :D

**Comment by mCodex** [comment] 2018-08-07 13:52
This fix is available on latest beta version (5.2.5). 

```
yarn add react-native-sensitive-info@beta
```

Tks @grigorigoldman

**Closed** 2018-10-08 13:56 UTC
Labels: iOS
